version: "3.7"
services:
  customer-service:
    build: customer-service
    container_name: customer_service
    image: florin_mugur/spring-azure-microservices
    environment:
      - API_KEY=local_api_key
    ports:
      - "8080:8080"